# Generated by Django 2.1.4 on 2019-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0020_auto_20190813_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTCRecords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('protocol', models.CharField(blank=True, max_length=12, null=True)),
                ('count_number', models.CharField(blank=True, max_length=6, null=True)),
                ('imei', models.CharField(max_length=20)),
                ('obd_header', models.CharField(blank=True, max_length=6, null=True)),
                ('obd_message_type', models.CharField(blank=True, max_length=10, null=True)),
                ('sae_standard', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=10, null=True)),
                ('error_code_status', models.IntegerField(blank=True, null=True)),
                ('checksum', models.IntegerField(blank=True, null=True)),
                ('send_time', models.BigIntegerField(blank=True, null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'dignosis_trouble_code',
            },
        ),
        migrations.AddIndex(
            model_name='dtcrecords',
            index=models.Index(fields=['date', 'imei', 'send_time', 'record_date'], name='dignosis_tr_date_9f4f29_idx'),
        ),
    ]
